CREATE TABLE IF NOT EXISTS "__EFMigrationsHistory" (
    "MigrationId" character varying(150) NOT NULL,
    "ProductVersion" character varying(32) NOT NULL,
    CONSTRAINT "PK___EFMigrationsHistory" PRIMARY KEY ("MigrationId")
);

START TRANSACTION;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260314140446_InitialIdentity') THEN
    CREATE TABLE "AspNetRoles" (
        "Id" uuid NOT NULL,
        "Name" character varying(256),
        "NormalizedName" character varying(256),
        "ConcurrencyStamp" text,
        CONSTRAINT "PK_AspNetRoles" PRIMARY KEY ("Id")
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260314140446_InitialIdentity') THEN
    CREATE TABLE "AspNetUsers" (
        "Id" uuid NOT NULL,
        "DisplayName" text NOT NULL,
        "IsEnabled" boolean NOT NULL,
        "UserName" character varying(256),
        "NormalizedUserName" character varying(256),
        "Email" character varying(256),
        "NormalizedEmail" character varying(256),
        "EmailConfirmed" boolean NOT NULL,
        "PasswordHash" text,
        "SecurityStamp" text,
        "ConcurrencyStamp" text,
        "PhoneNumber" text,
        "PhoneNumberConfirmed" boolean NOT NULL,
        "TwoFactorEnabled" boolean NOT NULL,
        "LockoutEnd" timestamp with time zone,
        "LockoutEnabled" boolean NOT NULL,
        "AccessFailedCount" integer NOT NULL,
        CONSTRAINT "PK_AspNetUsers" PRIMARY KEY ("Id")
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260314140446_InitialIdentity') THEN
    CREATE TABLE tenants (
        "Id" uuid NOT NULL,
        "Name" character varying(200) NOT NULL,
        "Slug" character varying(100) NOT NULL,
        "IsEnabled" boolean NOT NULL,
        CONSTRAINT "PK_tenants" PRIMARY KEY ("Id")
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260314140446_InitialIdentity') THEN
    CREATE TABLE "AspNetRoleClaims" (
        "Id" integer GENERATED BY DEFAULT AS IDENTITY,
        "RoleId" uuid NOT NULL,
        "ClaimType" text,
        "ClaimValue" text,
        CONSTRAINT "PK_AspNetRoleClaims" PRIMARY KEY ("Id"),
        CONSTRAINT "FK_AspNetRoleClaims_AspNetRoles_RoleId" FOREIGN KEY ("RoleId") REFERENCES "AspNetRoles" ("Id") ON DELETE CASCADE
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260314140446_InitialIdentity') THEN
    CREATE TABLE "AspNetUserClaims" (
        "Id" integer GENERATED BY DEFAULT AS IDENTITY,
        "UserId" uuid NOT NULL,
        "ClaimType" text,
        "ClaimValue" text,
        CONSTRAINT "PK_AspNetUserClaims" PRIMARY KEY ("Id"),
        CONSTRAINT "FK_AspNetUserClaims_AspNetUsers_UserId" FOREIGN KEY ("UserId") REFERENCES "AspNetUsers" ("Id") ON DELETE CASCADE
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260314140446_InitialIdentity') THEN
    CREATE TABLE "AspNetUserLogins" (
        "LoginProvider" text NOT NULL,
        "ProviderKey" text NOT NULL,
        "ProviderDisplayName" text,
        "UserId" uuid NOT NULL,
        CONSTRAINT "PK_AspNetUserLogins" PRIMARY KEY ("LoginProvider", "ProviderKey"),
        CONSTRAINT "FK_AspNetUserLogins_AspNetUsers_UserId" FOREIGN KEY ("UserId") REFERENCES "AspNetUsers" ("Id") ON DELETE CASCADE
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260314140446_InitialIdentity') THEN
    CREATE TABLE "AspNetUserRoles" (
        "UserId" uuid NOT NULL,
        "RoleId" uuid NOT NULL,
        CONSTRAINT "PK_AspNetUserRoles" PRIMARY KEY ("UserId", "RoleId"),
        CONSTRAINT "FK_AspNetUserRoles_AspNetRoles_RoleId" FOREIGN KEY ("RoleId") REFERENCES "AspNetRoles" ("Id") ON DELETE CASCADE,
        CONSTRAINT "FK_AspNetUserRoles_AspNetUsers_UserId" FOREIGN KEY ("UserId") REFERENCES "AspNetUsers" ("Id") ON DELETE CASCADE
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260314140446_InitialIdentity') THEN
    CREATE TABLE "AspNetUserTokens" (
        "UserId" uuid NOT NULL,
        "LoginProvider" text NOT NULL,
        "Name" text NOT NULL,
        "Value" text,
        CONSTRAINT "PK_AspNetUserTokens" PRIMARY KEY ("UserId", "LoginProvider", "Name"),
        CONSTRAINT "FK_AspNetUserTokens_AspNetUsers_UserId" FOREIGN KEY ("UserId") REFERENCES "AspNetUsers" ("Id") ON DELETE CASCADE
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260314140446_InitialIdentity') THEN
    CREATE TABLE user_tenant_memberships (
        "UserId" uuid NOT NULL,
        "TenantId" uuid NOT NULL,
        "RoleCode" character varying(100) NOT NULL,
        "IsDefault" boolean NOT NULL,
        CONSTRAINT "PK_user_tenant_memberships" PRIMARY KEY ("UserId", "TenantId"),
        CONSTRAINT "FK_user_tenant_memberships_AspNetUsers_UserId" FOREIGN KEY ("UserId") REFERENCES "AspNetUsers" ("Id") ON DELETE CASCADE,
        CONSTRAINT "FK_user_tenant_memberships_tenants_TenantId" FOREIGN KEY ("TenantId") REFERENCES tenants ("Id") ON DELETE CASCADE
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260314140446_InitialIdentity') THEN
    CREATE INDEX "IX_AspNetRoleClaims_RoleId" ON "AspNetRoleClaims" ("RoleId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260314140446_InitialIdentity') THEN
    CREATE UNIQUE INDEX "RoleNameIndex" ON "AspNetRoles" ("NormalizedName");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260314140446_InitialIdentity') THEN
    CREATE INDEX "IX_AspNetUserClaims_UserId" ON "AspNetUserClaims" ("UserId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260314140446_InitialIdentity') THEN
    CREATE INDEX "IX_AspNetUserLogins_UserId" ON "AspNetUserLogins" ("UserId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260314140446_InitialIdentity') THEN
    CREATE INDEX "IX_AspNetUserRoles_RoleId" ON "AspNetUserRoles" ("RoleId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260314140446_InitialIdentity') THEN
    CREATE INDEX "EmailIndex" ON "AspNetUsers" ("NormalizedEmail");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260314140446_InitialIdentity') THEN
    CREATE UNIQUE INDEX "UserNameIndex" ON "AspNetUsers" ("NormalizedUserName");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260314140446_InitialIdentity') THEN
    CREATE UNIQUE INDEX "IX_tenants_Slug" ON tenants ("Slug");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260314140446_InitialIdentity') THEN
    CREATE INDEX "IX_user_tenant_memberships_TenantId" ON user_tenant_memberships ("TenantId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260314140446_InitialIdentity') THEN
    INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
    VALUES ('20260314140446_InitialIdentity', '10.0.5');
    END IF;
END $EF$;
COMMIT;

START TRANSACTION;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260315015112_AddRegistrationProvisioning') THEN
    CREATE TABLE "JobSeekerProfiles" (
        "Id" character varying(64) NOT NULL,
        "UserId" uuid NOT NULL,
        "Headline" character varying(250),
        "Summary" character varying(4000),
        "CurrentLocation" character varying(250),
        "PreferredLocation" character varying(250),
        "LinkedInUrl" character varying(500),
        "ResumeFileId" character varying(128),
        "OpenToWork" boolean NOT NULL,
        "DesiredSalaryFrom" numeric(18,2),
        "DesiredSalaryTo" numeric(18,2),
        "DesiredSalaryCurrency" integer,
        "CreatedUtc" timestamp with time zone NOT NULL,
        "UpdatedUtc" timestamp with time zone,
        "CreatedByUserId" character varying(64),
        "UpdatedByUserId" character varying(64),
        CONSTRAINT "PK_JobSeekerProfiles" PRIMARY KEY ("Id"),
        CONSTRAINT "FK_JobSeekerProfiles_AspNetUsers_UserId" FOREIGN KEY ("UserId") REFERENCES "AspNetUsers" ("Id") ON DELETE CASCADE
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260315015112_AddRegistrationProvisioning') THEN
    CREATE TABLE "CompanyRecruiterRelationships" (
        "Id" character varying(64) NOT NULL,
        "CompanyOrganisationId" character varying(64) NOT NULL,
        "RecruiterOrganisationId" character varying(64) NOT NULL,
        "Status" integer NOT NULL,
        "Scope" integer NOT NULL,
        "RecruiterCanCreateUnclaimedCompanyJobs" boolean NOT NULL,
        "RecruiterCanPublishJobs" boolean NOT NULL,
        "RecruiterCanManageCandidates" boolean NOT NULL,
        "RequestedByUserId" character varying(64),
        "ApprovedByUserId" character varying(64),
        "ApprovedUtc" timestamp with time zone,
        "Notes" character varying(4000),
        "CreatedUtc" timestamp with time zone NOT NULL,
        "UpdatedUtc" timestamp with time zone,
        "CreatedByUserId" character varying(64),
        "UpdatedByUserId" character varying(64),
        CONSTRAINT "PK_CompanyRecruiterRelationships" PRIMARY KEY ("Id")
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260315015112_AddRegistrationProvisioning') THEN
    CREATE TABLE "JobApplications" (
        "Id" character varying(64) NOT NULL,
        "JobId" character varying(64) NOT NULL,
        "UserId" uuid NOT NULL,
        "Status" integer NOT NULL,
        "ResumeFileId" character varying(128),
        "CoverLetter" character varying(20000),
        "SubmittedUtc" timestamp with time zone NOT NULL,
        "LastStatusChangedUtc" timestamp with time zone,
        "Source" character varying(100),
        "Notes" character varying(4000),
        "CreatedUtc" timestamp with time zone NOT NULL,
        "UpdatedUtc" timestamp with time zone,
        "CreatedByUserId" character varying(64),
        "UpdatedByUserId" character varying(64),
        CONSTRAINT "PK_JobApplications" PRIMARY KEY ("Id"),
        CONSTRAINT "FK_JobApplications_AspNetUsers_UserId" FOREIGN KEY ("UserId") REFERENCES "AspNetUsers" ("Id") ON DELETE RESTRICT
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260315015112_AddRegistrationProvisioning') THEN
    CREATE TABLE "Jobs" (
        "Id" character varying(64) NOT NULL,
        "OwnedByOrganisationId" character varying(64) NOT NULL,
        "ManagedByOrganisationId" character varying(64),
        "CompanyRecruiterRelationshipId" character varying(64),
        "CreatedByIdentityUserId" uuid NOT NULL,
        "CreatedByType" integer NOT NULL,
        "Status" integer NOT NULL,
        "Visibility" integer NOT NULL,
        "Title" character varying(250) NOT NULL,
        "ReferenceCode" character varying(100),
        "Department" character varying(150),
        "LocationText" character varying(250),
        "WorkplaceType" integer NOT NULL,
        "EmploymentType" integer NOT NULL,
        "Description" character varying(20000) NOT NULL,
        "Requirements" character varying(20000),
        "Benefits" character varying(20000),
        "SalaryFrom" numeric(18,2),
        "SalaryTo" numeric(18,2),
        "SalaryCurrency" integer,
        "PublishedUtc" timestamp with time zone,
        "ClosedUtc" timestamp with time zone,
        "ApprovedByUserId" uuid,
        "ApprovedUtc" timestamp with time zone,
        "CreatedForUnclaimedCompany" boolean NOT NULL,
        "CreatedUtc" timestamp with time zone NOT NULL,
        "UpdatedUtc" timestamp with time zone,
        "CreatedByUserId" character varying(64),
        "UpdatedByUserId" character varying(64),
        CONSTRAINT "PK_Jobs" PRIMARY KEY ("Id"),
        CONSTRAINT "FK_Jobs_AspNetUsers_CreatedByIdentityUserId" FOREIGN KEY ("CreatedByIdentityUserId") REFERENCES "AspNetUsers" ("Id") ON DELETE RESTRICT,
        CONSTRAINT "FK_Jobs_CompanyRecruiterRelationships_CompanyRecruiterRelation~" FOREIGN KEY ("CompanyRecruiterRelationshipId") REFERENCES "CompanyRecruiterRelationships" ("Id") ON DELETE SET NULL
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260315015112_AddRegistrationProvisioning') THEN
    CREATE TABLE "OrganisationClaimRequests" (
        "Id" character varying(64) NOT NULL,
        "OrganisationId" character varying(64) NOT NULL,
        "RequestedByUserId" uuid NOT NULL,
        "EmailUsed" character varying(320) NOT NULL,
        "EmailDomain" character varying(255) NOT NULL,
        "Status" integer NOT NULL,
        "VerificationMethod" integer NOT NULL,
        "VerificationToken" character varying(200),
        "VerifiedUtc" timestamp with time zone,
        "ApprovedByUserId" uuid,
        "ApprovedUtc" timestamp with time zone,
        "RejectionReason" character varying(1000),
        "CreatedUtc" timestamp with time zone NOT NULL,
        "UpdatedUtc" timestamp with time zone,
        "CreatedByUserId" character varying(64),
        "UpdatedByUserId" character varying(64),
        CONSTRAINT "PK_OrganisationClaimRequests" PRIMARY KEY ("Id"),
        CONSTRAINT "FK_OrganisationClaimRequests_AspNetUsers_RequestedByUserId" FOREIGN KEY ("RequestedByUserId") REFERENCES "AspNetUsers" ("Id") ON DELETE RESTRICT
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260315015112_AddRegistrationProvisioning') THEN
    CREATE TABLE "OrganisationDomains" (
        "Id" character varying(64) NOT NULL,
        "OrganisationId" character varying(64) NOT NULL,
        "Domain" character varying(255) NOT NULL,
        "NormalizedDomain" character varying(255) NOT NULL,
        "IsPrimary" boolean NOT NULL,
        "Status" integer NOT NULL,
        "VerificationMethod" integer NOT NULL,
        "TrustLevel" integer NOT NULL,
        "VerificationToken" character varying(200),
        "VerificationDnsRecordName" character varying(255),
        "VerificationDnsRecordValue" character varying(500),
        "VerificationEmailAddress" character varying(320),
        "VerificationRequestedUtc" timestamp with time zone,
        "VerifiedUtc" timestamp with time zone,
        "VerifiedByUserId" character varying(64),
        "CreatedUtc" timestamp with time zone NOT NULL,
        "UpdatedUtc" timestamp with time zone,
        "CreatedByUserId" character varying(64),
        "UpdatedByUserId" character varying(64),
        CONSTRAINT "PK_OrganisationDomains" PRIMARY KEY ("Id")
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260315015112_AddRegistrationProvisioning') THEN
    CREATE TABLE "Organisations" (
        "Id" character varying(64) NOT NULL,
        "Type" integer NOT NULL,
        "Status" integer NOT NULL,
        "ClaimStatus" integer NOT NULL,
        "Name" character varying(250) NOT NULL,
        "NormalizedName" character varying(250) NOT NULL,
        "LegalName" character varying(250),
        "WebsiteUrl" character varying(500),
        "PrimaryDomainId" character varying(64),
        "IsProvisionedByRecruiter" boolean NOT NULL,
        "ClaimedByUserId" character varying(64),
        "ClaimedUtc" timestamp with time zone,
        "PrimaryContactName" character varying(250),
        "PrimaryContactEmail" character varying(320),
        "PrimaryContactPhone" character varying(50),
        "CreatedUtc" timestamp with time zone NOT NULL,
        "UpdatedUtc" timestamp with time zone,
        "CreatedByUserId" character varying(64),
        "UpdatedByUserId" character varying(64),
        CONSTRAINT "PK_Organisations" PRIMARY KEY ("Id"),
        CONSTRAINT "FK_Organisations_OrganisationDomains_PrimaryDomainId" FOREIGN KEY ("PrimaryDomainId") REFERENCES "OrganisationDomains" ("Id") ON DELETE RESTRICT
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260315015112_AddRegistrationProvisioning') THEN
    CREATE TABLE "OrganisationInvitations" (
        "Id" character varying(64) NOT NULL,
        "Type" integer NOT NULL,
        "Status" integer NOT NULL,
        "OrganisationId" character varying(64) NOT NULL,
        "Email" character varying(320) NOT NULL,
        "NormalizedEmail" character varying(320) NOT NULL,
        "EmailDomain" character varying(255) NOT NULL,
        "Token" character varying(200) NOT NULL,
        "ExpiresUtc" timestamp with time zone NOT NULL,
        "CompanyRole" integer,
        "RecruiterRole" integer,
        "AllowClaimAsOwner" boolean NOT NULL,
        "AcceptedByUserId" character varying(64),
        "AcceptedUtc" timestamp with time zone,
        "CreatedUtc" timestamp with time zone NOT NULL,
        "UpdatedUtc" timestamp with time zone,
        "CreatedByUserId" character varying(64),
        "UpdatedByUserId" character varying(64),
        CONSTRAINT "PK_OrganisationInvitations" PRIMARY KEY ("Id"),
        CONSTRAINT "FK_OrganisationInvitations_Organisations_OrganisationId" FOREIGN KEY ("OrganisationId") REFERENCES "Organisations" ("Id") ON DELETE CASCADE
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260315015112_AddRegistrationProvisioning') THEN
    CREATE TABLE "OrganisationMemberships" (
        "Id" character varying(64) NOT NULL,
        "OrganisationId" character varying(64) NOT NULL,
        "UserId" uuid NOT NULL,
        "Status" integer NOT NULL,
        "CompanyRole" integer,
        "RecruiterRole" integer,
        "IsOwner" boolean NOT NULL,
        "JoinedUtc" timestamp with time zone NOT NULL,
        "LeftUtc" timestamp with time zone,
        "CreatedUtc" timestamp with time zone NOT NULL,
        "UpdatedUtc" timestamp with time zone,
        "CreatedByUserId" character varying(64),
        "UpdatedByUserId" character varying(64),
        CONSTRAINT "PK_OrganisationMemberships" PRIMARY KEY ("Id"),
        CONSTRAINT "FK_OrganisationMemberships_AspNetUsers_UserId" FOREIGN KEY ("UserId") REFERENCES "AspNetUsers" ("Id") ON DELETE RESTRICT,
        CONSTRAINT "FK_OrganisationMemberships_Organisations_OrganisationId" FOREIGN KEY ("OrganisationId") REFERENCES "Organisations" ("Id") ON DELETE CASCADE
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260315015112_AddRegistrationProvisioning') THEN
    CREATE UNIQUE INDEX "IX_CompanyRecruiterRelationships_CompanyOrganisationId_Recruit~" ON "CompanyRecruiterRelationships" ("CompanyOrganisationId", "RecruiterOrganisationId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260315015112_AddRegistrationProvisioning') THEN
    CREATE INDEX "IX_CompanyRecruiterRelationships_RecruiterOrganisationId" ON "CompanyRecruiterRelationships" ("RecruiterOrganisationId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260315015112_AddRegistrationProvisioning') THEN
    CREATE INDEX "IX_JobApplications_JobId_Status" ON "JobApplications" ("JobId", "Status");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260315015112_AddRegistrationProvisioning') THEN
    CREATE UNIQUE INDEX "IX_JobApplications_JobId_UserId" ON "JobApplications" ("JobId", "UserId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260315015112_AddRegistrationProvisioning') THEN
    CREATE INDEX "IX_JobApplications_UserId" ON "JobApplications" ("UserId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260315015112_AddRegistrationProvisioning') THEN
    CREATE INDEX "IX_Jobs_CompanyRecruiterRelationshipId" ON "Jobs" ("CompanyRecruiterRelationshipId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260315015112_AddRegistrationProvisioning') THEN
    CREATE INDEX "IX_Jobs_CreatedByIdentityUserId" ON "Jobs" ("CreatedByIdentityUserId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260315015112_AddRegistrationProvisioning') THEN
    CREATE INDEX "IX_Jobs_ManagedByOrganisationId_Status" ON "Jobs" ("ManagedByOrganisationId", "Status");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260315015112_AddRegistrationProvisioning') THEN
    CREATE INDEX "IX_Jobs_OwnedByOrganisationId_Status" ON "Jobs" ("OwnedByOrganisationId", "Status");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260315015112_AddRegistrationProvisioning') THEN
    CREATE INDEX "IX_Jobs_ReferenceCode" ON "Jobs" ("ReferenceCode");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260315015112_AddRegistrationProvisioning') THEN
    CREATE INDEX "IX_Jobs_Visibility_Status" ON "Jobs" ("Visibility", "Status");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260315015112_AddRegistrationProvisioning') THEN
    CREATE UNIQUE INDEX "IX_JobSeekerProfiles_UserId" ON "JobSeekerProfiles" ("UserId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260315015112_AddRegistrationProvisioning') THEN
    CREATE INDEX "IX_OrganisationClaimRequests_EmailDomain_Status" ON "OrganisationClaimRequests" ("EmailDomain", "Status");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260315015112_AddRegistrationProvisioning') THEN
    CREATE INDEX "IX_OrganisationClaimRequests_OrganisationId_Status" ON "OrganisationClaimRequests" ("OrganisationId", "Status");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260315015112_AddRegistrationProvisioning') THEN
    CREATE INDEX "IX_OrganisationClaimRequests_RequestedByUserId" ON "OrganisationClaimRequests" ("RequestedByUserId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260315015112_AddRegistrationProvisioning') THEN
    CREATE UNIQUE INDEX "IX_OrganisationDomains_NormalizedDomain" ON "OrganisationDomains" ("NormalizedDomain");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260315015112_AddRegistrationProvisioning') THEN
    CREATE INDEX "IX_OrganisationDomains_OrganisationId_IsPrimary" ON "OrganisationDomains" ("OrganisationId", "IsPrimary");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260315015112_AddRegistrationProvisioning') THEN
    CREATE INDEX "IX_OrganisationInvitations_OrganisationId_NormalizedEmail_Type~" ON "OrganisationInvitations" ("OrganisationId", "NormalizedEmail", "Type", "Status");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260315015112_AddRegistrationProvisioning') THEN
    CREATE UNIQUE INDEX "IX_OrganisationInvitations_Token" ON "OrganisationInvitations" ("Token");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260315015112_AddRegistrationProvisioning') THEN
    CREATE INDEX "IX_OrganisationMemberships_OrganisationId_IsOwner" ON "OrganisationMemberships" ("OrganisationId", "IsOwner");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260315015112_AddRegistrationProvisioning') THEN
    CREATE UNIQUE INDEX "IX_OrganisationMemberships_OrganisationId_UserId" ON "OrganisationMemberships" ("OrganisationId", "UserId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260315015112_AddRegistrationProvisioning') THEN
    CREATE INDEX "IX_OrganisationMemberships_UserId" ON "OrganisationMemberships" ("UserId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260315015112_AddRegistrationProvisioning') THEN
    CREATE INDEX "IX_Organisations_PrimaryDomainId" ON "Organisations" ("PrimaryDomainId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260315015112_AddRegistrationProvisioning') THEN
    CREATE INDEX "IX_Organisations_Type_NormalizedName" ON "Organisations" ("Type", "NormalizedName");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260315015112_AddRegistrationProvisioning') THEN
    ALTER TABLE "CompanyRecruiterRelationships" ADD CONSTRAINT "FK_CompanyRecruiterRelationships_Organisations_CompanyOrganisa~" FOREIGN KEY ("CompanyOrganisationId") REFERENCES "Organisations" ("Id") ON DELETE RESTRICT;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260315015112_AddRegistrationProvisioning') THEN
    ALTER TABLE "CompanyRecruiterRelationships" ADD CONSTRAINT "FK_CompanyRecruiterRelationships_Organisations_RecruiterOrgani~" FOREIGN KEY ("RecruiterOrganisationId") REFERENCES "Organisations" ("Id") ON DELETE RESTRICT;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260315015112_AddRegistrationProvisioning') THEN
    ALTER TABLE "JobApplications" ADD CONSTRAINT "FK_JobApplications_Jobs_JobId" FOREIGN KEY ("JobId") REFERENCES "Jobs" ("Id") ON DELETE CASCADE;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260315015112_AddRegistrationProvisioning') THEN
    ALTER TABLE "Jobs" ADD CONSTRAINT "FK_Jobs_Organisations_ManagedByOrganisationId" FOREIGN KEY ("ManagedByOrganisationId") REFERENCES "Organisations" ("Id") ON DELETE RESTRICT;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260315015112_AddRegistrationProvisioning') THEN
    ALTER TABLE "Jobs" ADD CONSTRAINT "FK_Jobs_Organisations_OwnedByOrganisationId" FOREIGN KEY ("OwnedByOrganisationId") REFERENCES "Organisations" ("Id") ON DELETE RESTRICT;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260315015112_AddRegistrationProvisioning') THEN
    ALTER TABLE "OrganisationClaimRequests" ADD CONSTRAINT "FK_OrganisationClaimRequests_Organisations_OrganisationId" FOREIGN KEY ("OrganisationId") REFERENCES "Organisations" ("Id") ON DELETE RESTRICT;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260315015112_AddRegistrationProvisioning') THEN
    ALTER TABLE "OrganisationDomains" ADD CONSTRAINT "FK_OrganisationDomains_Organisations_OrganisationId" FOREIGN KEY ("OrganisationId") REFERENCES "Organisations" ("Id") ON DELETE CASCADE;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260315015112_AddRegistrationProvisioning') THEN
    INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
    VALUES ('20260315015112_AddRegistrationProvisioning', '10.0.5');
    END IF;
END $EF$;
COMMIT;

